@startuml

class Core {
    + Core()
    + ~Core()

    + void init()
    + void run()

    - engine::ecs::Universe& _universe
}

enum BUTTON_ID {
    GUI_MENU_PLAY = 1,
    GUI_MENU_QUIT,
    GUI_MENU_HTP,
    GUI_MENU_OPT,
    GUI_SELECT_VALID,
    GUI_SELECT_P1,
    GUI_SELECT_P2,
    GUI_SELECT_P3,
    GUI_SELECT_P4,
    GUI_SELECT_KB_P1_UP,
    GUI_SELECT_KB_P1_DOWN,
    GUI_SELECT_KB_P1_LEFT,
    GUI_SELECT_KB_P1_RIGHT,
    GUI_SELECT_KB_P1_BOMB,

    GUI_SELECT_KB_P2_UP,
    GUI_SELECT_KB_P2_DOWN,
    GUI_SELECT_KB_P2_LEFT,
    GUI_SELECT_KB_P2_RIGHT,
    GUI_SELECT_KB_P2_BOMB,

    GUI_SELECT_KB_P3_UP,
    GUI_SELECT_KB_P3_DOWN,
    GUI_SELECT_KB_P3_LEFT,
    GUI_SELECT_KB_P3_RIGHT,
    GUI_SELECT_KB_P3_BOMB,

    GUI_SELECT_KB_P4_UP,
    GUI_SELECT_KB_P4_DOWN,
    GUI_SELECT_KB_P4_LEFT,
    GUI_SELECT_KB_P4_RIGHT,
    GUI_SELECT_KB_P4_BOMB,


}

class Menu {
    + Menu() = delete
    + ~Menu() = delete

    + static void init()
    + static void reset()
}

class PlayerSelector {
    + PlayerSelector() = delete
    + ~PlayerSelector() = delete

    + static void init()
    + static void reset()
}

class BomberMan {
    + BomberMan) = delete
    + ~BomberMan() = delete

    + static void init()
    + static void reset()

    - std::map
}

class KeyBinding {
    + KeyBinding(irr::EKEY_CODE up = irr::KEY_Z, irr::EKEY_CODE down = irr::KEY_S, irr::EKEY_CODE left = irr::KEY_Q, irr::EKEY_CODE right = irr::KEY_D, irr::EKEY_CODE bomb = irr::KEY_SPACE)
    + KeyBinding(const KeyBinding& key) = default
    + ~KeyBinding()

    + std::map<std::string, irr::EKEY_CODE> keys
}

namespace engine {

    namespace event {
        class Input {
            + Input()
            + ~Input()
        }

        class Collision {
            + Collision()
            + ~Collision()
        }

        class Close {
            + Close()
            + ~Close()
        }
    }

    namespace ecs {
        'using Entity = unsigned int
        'const Entity MAX_ENTITIES = 1000
        'using ComponentType = unsigned int
        'const ComponentType MAX_COMPONENTS = 32
        'using Signature = std::bitset<MAX_COMPONENTS>

        class Universe {
            + Universe()
            + ~Universe()

            + WorldManager* createWorldManager(const std::string& name)
            + bool hasWorldManager(const std::string& name) const
            + WorldManager* getWorldManager(const std::string& name) const
            + WorldManager* getCurrentWorldManager() const
            + void setCurrentWorldManager(const std::string& name)
            + void deleteWorldManager(const std::string& name)

            - std::map<std::string, std::unique_ptr<WorldManager>> _worldManagers
            - std::string _currentWorldManager
            - EventReceiver _eventReceiver
            - irr::IrrlichtDevice *device
        }
        Universe <-- WorldManager

        class EventReceiver {
            + EventReceiver(Universe *universe)
            + ~EventReceiver()

            + bool OnEvent(const SEvent& event) override

            - Universe *_universe
        }
        irr::IEventReceiver <|-- EventReceiver

        class WorldManager {
            + WorldManager()
            + ~WorldManager() = default

            + Entity createEntity()
            + void destroyEntity(Entity entity)

            + template<typename T> void registerComponent()
            + template<typename T> void addComponent(Entity entity, T component)
            + template<typename T> void removeComponent(Entity entity)
            + template<typename T> T& getComponent(Entity entity)
            + template<typename T> ComponentType getComponentType()

            + template<typename T> std::shared_ptr<T> registerSystem()
            + template<typename T> void setSystemSignature(Signature signature)

            + template<typename T, typename E> void subscribe(T& subscriber, Callback<T, E> callback)
            + void unsubscribe()

            + template<typname E> void publish(E& event)


            - eventManager _eventManager
            - std::unique_ptr<EntityManager> _entityManager
            - std::unique_ptr<SystemManager> _systemManager
            - std::unique_ptr<ComponentManager> _componentManager
        }

        class EntityManager {
            + EntityManager()
            + ~EntityManager() = default

            + Entity createEntity()
            + void destroyEntity(Entity entity)

            + void setSignature(Entity entity, Signature signature)
            + Signature& getSignature(Entity entity)

            - std::queue<Entity> _availableEntities
            - std::array<Signature, MAX_ENTITIES> _signatures
            - size_t _entitiesCount
        }

        class SystemManager {
            + SystemManager() = default
            + ~SystemManager() = default

            + template<typename T> std::shared_ptr<T> registerSystem()

            + template<typename T> void setSignature(Signature signature)

            + void entityDestroyed(Entity entity)

            + void entitySignatureChanged(Entity entity, Signature entSignature)

            - std::unordered_map<std::string, std::shared_ptr<System>> _systems
            - std::unordered_map<std::string, Signature> _signatures
        }

        class ComponentManager {
            + ComponentManager() = default
            + ~ComponentManager() = default

            + template<typename T> void registerComponent()

            - template<typename T> std::shared_ptr<ComponentArray<T>> getComponentArray()

            + template<typename T> ComponentType getComponentType()
            + template<typename T> void addComponent(Entity entity, T component)
            + template<typename T> void removeComponent(Entity entity)
            + template<typename T> T& getComponent(Entity entity)

            + void entityDestroyed(Entity entity)

            - std::unordered_map<std::string, ComponentType> _componentTypes
            - std::unordered_map<std::string, std::shared_ptr<IComponentArray>> _componentArrays
            - ComponentType _componentType
        }

        class IComponentArray {
            + virtual ~IComponentArray() = default

            + virtual void entityDestroyed(Entity entity) = 0
        }

        'template<typename T>
        class ComponentArray {
            + ComponentArray() = default
            + ~ComponentArray() override = default

            + void insert(Entity entity, T component)
            + void remove(Entity entity)
            + T& get(Entity entity)

            + void entityDestroyed(Entity entity) override

            - std::array<T, MAX_ENTITIES> _componentArray
            - std::unordered_map<Entity, size_t> _entityToIndex
            - std::unordered_map<size_t, Entity> _indexToEntity
            - size_t _size
        }
        IComponentArray <|-- ComponentArray

        class System {
            + System(ComponentManager *manager)
            + ~System()

            + ComponentManager *manager
            + std::set<Entity> entities
        }

        class EventManager {
            + EventManager() = default
            + ~EventManager()

            + template<typename T, typename E> void subscribe(T& subscriber, Callback<T, E> callback)
            + void unsubscribe()

            + template<typename E> void publish(E& event)

            - std::map<std::type_index, std::vector<ICallbackHandler*>*> _subscribers
        }

        class ICallbackHandler {
            + virtual ~ICallbackHandler() = default

            + virtual void call(AEvent& event) = 0
        }
        EventManager +-- ICallbackHandler

        'template<typename T, typename E> using Callback = void (T::*)(E&)
        'template<typename T, typename E>
        class CallbackHandler {
            + CallbackHandler(T& subscriber, Callback<T, E> callback)
            + ~CallbackHandler() override = default

            + void call(AEvent& event) override

            - T& _subscriber
            - Callback<T, E> _callback
        }
        EventManager +-- CallbackHandler
        ICallbackHandler <|-- CallbackHandler

        class AEvent {
            + AEvent() = delete
            + ~AEvent() = default
        }
        AEvent <|-- engine.event.Input
        AEvent <|-- engine.event.Close
        AEvent <|-- engine.event.Collision
    }

    namespace system {
        class Player {
            + Player(irr::ISceneManager* smgr)
            + ~Player()

            + void init()
            + void update()
            + void render()

            + irr::ISceneManager* smgr
        }
        engine.ecs.System <|-- User

        class CollisionBox {
            + CollisionBox()
            + ~CollisionBox()

            + void init()
            + void update()
            + void render()
        }
        engine.ecs.System <|-- CollisionBox

        class AI {
            + AI()
            + ~AI()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- AI

        class Music {
            + Music(ISceneManager* smgr)
            + ~Music()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- Music

        class Animation {
            + Animation(ISceneManager* smgr)
            + ~Animation()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- Animation

        class Movement {
            + Movement(ISceneManager* smgr)
            + ~Movement()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- Movement

        class Render {
            + Render(ISceneManager* smgr)
            + ~Render()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- Render

        class Physics {
            + Physics(ISceneManager* smgr)
            + ~Physics()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- Physics

        class Size {
            + Size(ISceneManager* smgr)
            + ~Size()

            + void init()
            + void update()
            + void render()

            + ISceneManager* smgr
        }
        engine.ecs.System <|-- Size

        class Image {
            + Image(irr:video::IVideoDriver* driver)
            + ~Image()

            + void init()
            + void update()
            + void render()

            + irr::video::IVideoDriver* driver
        }
    }

    namespace component {
        class Player {
            + Player(const KeyBinding& keybinding)
            + ~Player()

            + KeyBinding keys
        }

        class AI {
            + AI()
            + ~AI()
        }

        class Music {
            + Music()
            + ~Music()

            + sf::Music music
        }

        class Sound {
            + Sound()
            + ~Sound()

            + std::map<std::string, sf::Music>
        }

         class Particle {
            + Particle(irr::video::IVideoDriver *driver, irr::scene::IParticleSystemSceneNode *prtc, irr::vector3df pos, const irr::io::path &texture)
            + ~Particle()

            + irr::scene::IParticleSystemSceneNode *particle
        }

        class Motion {
            + Motion(float movementSpeed)
            + ~Motion()

            + float movementSpeed
            + irr::core::vector3df direction
        }

        class Animation {
            + Animation()
            + ~Animation()

            + std::map<std::string, std::pair<size_t, size_t>> animationRanges
        }

        class LookingView {
            + LookingView()
            + ~LookingView()

            + irr::core::vector3df direction
        }

        class Render3d {
            + Render(irr::ISceneNode* node)
            + ~Render()

            + irr::ISceneNode* node
        }

        class BombTimer {
            + BombTimer(irr::IrrlichtDevice *device, irr::u32 duration)
            + ~BombTimer()

            + irr::u32 timerStart
            + irr::u32 duration
        }

        class Stats {
            + Stats()
            + ~Stats()

            + size_t moveSpeed
            + size_t bombRadius
            + size_t maxBomb
            + bool wallPass
        }

        class Unbreakable {
            + Unbreakable()
            + ~Unbreakable()
        }

        class Lootable {
            + Lootable()
            + ~Lootable()
        }

        class BombStats {
            + BombStats (size_t bombRadius, bool wallPass)
            + ~BombStats()

            + size_t bombRadius
            + bool wallPass
        }

        class Owner {
            + Owner(const size_t ID)
            + ~Owner()

            + size_t entityID
        }

        class Transform {
            + Transform(irr::core::vector3df position)
            + ~Transform()

            + irr::core::vector3df position
        }

        class CollisionBox {
            + CollisionBox()
            + ~CollisionBox()
        }

        class Size {
            + Size(irr::core::vector3df size)
            + ~Size()

            + irr::core::vector3df size
        }

        class Text {
            + Text(irr::gui::irr::gui::IGUIEnvironment* gui, const wchar_t * text, const core::rect<s32> &rectangle, bool border = false, bool wordWrap = true, IGUIElement *parent = 0, s32 id = -1, bool fillBackground = false)
            + ~Text()

            + void setFont(const irr::io::path &path)

            + irr::gui::IGUIEnvironment* gui
            + irr::gui::IGUIStaticText* text
            + irr::gui::IGUIFont* font
        }

        class Button {
            + Button(irr::gui::IGUIEnvironment* gui, irr::core::rect<irr::s32> position, IGUIElement* parent = 0, s32 id = -1, const wchar_t* text = 0, const wchar_t* tooltipText = 0)
            + ~Button()

            + void setFont(const irr::io::path &path)
            + void setImage(irr::video::ITexture *texture)
            + void setPressedImage(irr::video::ITexture *texture)

            + irr::gui::IGUIEnvironment* gui
            + irr::gui::IGUIButton* button
            + irr::gui::IGUIFont *font
        }

        class MessageBox {
            + MessageBox(irr::gui::IGUIEnvironment* gui, const wchar_t *caption, const wchar_t *text, bool modal = true, irr::s32 flags = irr::gui::EMBF_OK, IGUIEnvironment* parent = 0, irr::s32 id = -1, irr::video::ITexture* image = 0)
            + ~MessageBox()

            + irr::gui::IGUIEnvironment* gui
            + irr:gui::IGUIWindow* messageBox
        }

        class Image {
            + Image(irr::video::IVideoDriver* driver, irr::io::path texture, irr::core::position2d<irr::s32> position, irr::core::rect<irr::s32> rect, irr::core::rect<irr::s32> *clipRect = 0, irr::video::SColor scolor = irr::video::SColor(255, 255, 255, 255), bool useAlphaChannelOfTexture = false )
            + ~Image()

            + irr::video::IVideoDriver* driver
            + irr::video::ITexture* image
            + irr::core::position2d<irr::s32> position
            + irr::core::rect<irr::s32> rect
            + irr::core::rect<irr::s32> *clipRect
            + irr::video::SColor scolor
            + bool useAlphaChannelOfTexture
        }
    }
}



@enduml
