name: Push

on:
  push:
    branches: [master]

jobs:

  fedora:
    runs-on: ubuntu-latest
    container: cyberryteam/epitech-docker:fedora

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cmake -B build && make -C build

  ubuntu:
    runs-on: ubuntu-latest
    container: cyberryteam/epitech-docker:ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cmake -B build && make -C build

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cmake -B build && cmake --build build

  push:
    needs: [fedora, ubuntu, windows]

    runs-on: [ubuntu-latest]

    env:
      REPOSITORY_OWNER: lucas.mathieux@epitech.eu
      REPOSITORY_NAME: OOP_indie_studio_2019

    steps:
      - uses: actions/checkout@v1

      - name: Inizialize
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Push
        run: |
          git push git@git.epitech.eu:/$REPOSITORY_OWNER/$REPOSITORY_NAME HEAD:master --force
